/**
 * backend/config/blockchain.js
 *
 * Blockchain Service — ethers.js v6 bridge
 * Connects the Node.js backend to the local Hardhat node.
 *
 * Responsibilities:
 *  - Initialise provider + signer (admin wallet)
 *  - Load deployed contract instances (LoyaltyToken, EcommercePayment)
 *  - Expose helper functions called by route handlers
 *  - Listen to on-chain events and mirror them to MongoDB
 */

const { ethers } = require("ethers");
const path = require("path");
const fs = require("fs");
require("dotenv").config();

// Load contract ABIs (generated by `npx hardhat compile`)
const ARTIFACTS_DIR = path.join(
  __dirname,
  "..",
  "..",
  "artifacts",
  "contracts",
);

function loadABI(contractName) {
  const artifactPath = path.join(
    ARTIFACTS_DIR,
    `${contractName}.sol`,
    `${contractName}.json`,
  );
  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `ABI not found for ${contractName}. Run 'npx hardhat compile' first.`,
    );
  }
  return JSON.parse(fs.readFileSync(artifactPath, "utf8")).abi;
}

// Load deployed addresses written by deploy.js
function loadAddresses() {
  const addressFile = path.join(__dirname, "..", "deployedAddresses.json");
  if (!fs.existsSync(addressFile)) {
    throw new Error(
      "deployedAddresses.json not found. Run 'npm run deploy' first.",
    );
  }
  return JSON.parse(fs.readFileSync(addressFile, "utf8"));
}

class BlockchainService {
  constructor() {
    this.provider = null;
    this.adminWallet = null;
    this.loyaltyToken = null;
    this.ecommerce = null;
    this.receipt = null;
    this.escrow = null;
    this.initialized = false;
  }

  async init() {
    try {
      // Connect to local Hardhat node
      const rpcUrl = process.env.HARDHAT_RPC_URL || "http://127.0.0.1:8545";
      this.provider = new ethers.JsonRpcProvider(rpcUrl);

      // Admin signer — Hardhat account[0]
      const adminKey =
        process.env.ADMIN_PRIVATE_KEY ||
        "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
      this.adminWallet = new ethers.Wallet(adminKey, this.provider);

      // Load addresses & ABIs
      const addresses = loadAddresses();
      const loyaltyABI = loadABI("LoyaltyToken");
      const ecommerceABI = loadABI("EcommercePayment");

      this.loyaltyToken = new ethers.Contract(
        addresses.contracts.LoyaltyToken,
        loyaltyABI,
        this.adminWallet,
      );

      this.ecommerce = new ethers.Contract(
        addresses.contracts.EcommercePayment,
        ecommerceABI,
        this.adminWallet,
      );

      // Optional (new) contracts — guarded so the backend still boots against
      // an older deployment that predates escrow / NFT receipts.
      if (addresses.contracts.PurchaseReceipt) {
        this.receipt = new ethers.Contract(
          addresses.contracts.PurchaseReceipt,
          loadABI("PurchaseReceipt"),
          this.adminWallet,
        );
      }
      if (addresses.contracts.PurchaseEscrow) {
        this.escrow = new ethers.Contract(
          addresses.contracts.PurchaseEscrow,
          loadABI("PurchaseEscrow"),
          this.adminWallet,
        );
      }

      this.initialized = true;
      console.log("✅  Blockchain service initialised");
      console.log(
        `    LoyaltyToken      : ${addresses.contracts.LoyaltyToken}`,
      );
      console.log(
        `    EcommercePayment  : ${addresses.contracts.EcommercePayment}`,
      );
      if (addresses.contracts.PurchaseReceipt) {
        console.log(
          `    PurchaseReceipt   : ${addresses.contracts.PurchaseReceipt}`,
        );
      }
      if (addresses.contracts.PurchaseEscrow) {
        console.log(
          `    PurchaseEscrow    : ${addresses.contracts.PurchaseEscrow}`,
        );
      }

      // Start event listeners
      this._listenToEvents();
    } catch (err) {
      console.error("❌  Blockchain service init failed:", err.message);
      // Non-fatal — backend still runs without blockchain for development
    }
  }

  // ── Event Listeners (mirror on-chain events to MongoDB) ──────────────────

  _listenToEvents() {
    if (!this.ecommerce) return;

    this.ecommerce.on(
      "PaymentCompleted",
      async (
        orderId,
        buyer,
        seller,
        sellerReceives,
        platformFee,
        tokensEarned,
        event,
      ) => {
        console.log(
          `⛓  [Event] PaymentCompleted — Order #${orderId} | Buyer: ${buyer} | Seller: ${seller}`,
        );
        try {
          // Dynamically import to avoid circular dep
          const { BlockchainLog } = require("../models/blockchainLog.model");
          await BlockchainLog.create({
            eventType: "PaymentCompleted",
            orderId: orderId.toString(),
            buyerAddress: buyer,
            sellerAddress: seller,
            sellerReceivesWei: sellerReceives.toString(),
            platformFeeWei: platformFee.toString(),
            tokensEarned: tokensEarned.toString(),
            txHash: event.log.transactionHash,
            blockNumber: event.log.blockNumber,
          });
        } catch (e) {
          console.error(
            "Failed to log PaymentCompleted to MongoDB:",
            e.message,
          );
        }
      },
    );

    this.loyaltyToken.on("TokensIssued", (customer, amount, reason) => {
      console.log(
        `🪙  [Event] TokensIssued — ${ethers.formatUnits(
          amount,
          18,
        )} LYT → ${customer} (${reason})`,
      );
    });

    this.loyaltyToken.on("TokensRedeemed", (customer, amount) => {
      console.log(
        `🔥  [Event] TokensRedeemed — ${ethers.formatUnits(
          amount,
          18,
        )} LYT burned by ${customer}`,
      );
    });
  }

  // ── Helpers called by route handlers ─────────────────────────────────────

  /**
   * Get a user-facing signer for a given private key (Hardhat account).
   * Used when a customer/seller initiates a blockchain transaction from the backend.
   */
  getSignerForKey(privateKey) {
    return new ethers.Wallet(privateKey, this.provider);
  }

  /**
   * Get a contract instance connected to a specific signer.
   */
  getEcommerceForSigner(signer) {
    return this.ecommerce.connect(signer);
  }

  /**
   * Get LYT token balance for an address (in whole LYT units).
   */
  async getTokenBalance(address) {
    if (!this.initialized) return 0n;
    return await this.loyaltyToken.getTokenBalance(address);
  }

  /**
   * Get all orders for a buyer from on-chain.
   */
  async getBuyerOrders(address) {
    if (!this.initialized) return [];
    const orderIds = await this.ecommerce.getBuyerOrders(address);
    const orders = await Promise.all(
      orderIds.map((id) => this.ecommerce.getOrder(id)),
    );
    return orders;
  }

  /**
   * Preview hybrid payment cost.
   */
  async previewHybridCost(totalPriceWei, tokenAmount) {
    if (!this.initialized) throw new Error("Blockchain not initialised");
    return await this.ecommerce.previewHybridCost(totalPriceWei, tokenAmount);
  }

  /**
   * Format wei to ETH string.
   */
  formatEth(wei) {
    return ethers.formatEther(wei);
  }

  /**
   * Parse ETH string to wei.
   */
  parseEth(eth) {
    return ethers.parseEther(eth.toString());
  }

  /**
   * Platform/admin wallet address — used as the destination for
   * ETH → currency swaps and the source for currency → ETH swaps.
   */
  get adminAddress() {
    return this.adminWallet ? this.adminWallet.address : null;
  }

  /**
   * Get on-chain ETH balance for an address (as a decimal ETH string).
   */
  async getEthBalance(address) {
    if (!this.provider || !address) return "0";
    try {
      const balance = await this.provider.getBalance(address);
      return ethers.formatEther(balance);
    } catch {
      return "0";
    }
  }

  /**
   * Send ETH from the admin/platform wallet to a recipient (used when a
   * customer swaps RM/Elixir back into ETH, crediting their MetaMask account).
   * @returns {Promise<string>} transaction hash
   */
  async sendEthFromAdmin(toAddress, ethAmount) {
    if (!this.initialized || !this.adminWallet) {
      throw new Error("Blockchain service not available for ETH payout");
    }
    if (!ethers.isAddress(toAddress)) {
      throw new Error("Invalid recipient address");
    }
    const tx = await this.adminWallet.sendTransaction({
      to: toAddress,
      value: ethers.parseEther(ethAmount.toString()),
    });
    const receipt = await tx.wait();
    return receipt.hash;
  }

  /**
   * Verify that a MetaMask transaction actually sent at least `minEth`
   * to the platform admin address. Returns true on success.
   * Used to confirm an ETH → currency swap before crediting the customer.
   */
  async verifyIncomingEth(txHash, minEth) {
    if (!this.provider) throw new Error("Blockchain provider unavailable");
    if (!txHash) throw new Error("Missing transaction hash");

    const tx = await this.provider.getTransaction(txHash);
    if (!tx) throw new Error("Transaction not found on-chain");

    // Wait for it to be mined (Hardhat mines instantly)
    const receipt = await this.provider.getTransactionReceipt(txHash);
    if (!receipt || receipt.status !== 1) {
      throw new Error("Transaction not confirmed");
    }

    const toOk =
      tx.to && this.adminAddress &&
      tx.to.toLowerCase() === this.adminAddress.toLowerCase();
    if (!toOk) {
      throw new Error("Transaction was not sent to the platform address");
    }

    const minWei = ethers.parseEther(minEth.toString());
    if (tx.value < minWei) {
      throw new Error("Transaction amount is less than the swap amount");
    }

    return true;
  }

  /**
   * Verify that a confirmed transaction sent at least `minEth` to a specific
   * recipient address. Used for peer-to-peer ETH transfers via MetaMask.
   */
  async verifyEthTransfer(txHash, expectedTo, minEth) {
    if (!this.provider) throw new Error("Blockchain provider unavailable");
    if (!txHash) throw new Error("Missing transaction hash");

    const tx = await this.provider.getTransaction(txHash);
    if (!tx) throw new Error("Transaction not found on-chain");

    const receipt = await this.provider.getTransactionReceipt(txHash);
    if (!receipt || receipt.status !== 1) {
      throw new Error("Transaction not confirmed");
    }

    const toOk =
      tx.to && expectedTo && tx.to.toLowerCase() === expectedTo.toLowerCase();
    if (!toOk) {
      throw new Error("Transaction recipient does not match");
    }

    const minWei = ethers.parseEther(minEth.toString());
    if (tx.value < minWei) {
      throw new Error("Transaction amount is less than the transfer amount");
    }

    return true;
  }

  // ── LYT (Elixir) token helpers ────────────────────────────────────────────

  /**
   * Deployed LoyaltyToken (Elixir) contract address.
   */
  get loyaltyTokenAddress() {
    return this.loyaltyToken ? this.loyaltyToken.target : null;
  }

  /**
   * Raw LYT balance (in wei-units, 18 decimals) for an address.
   */
  async getLytBalanceWei(address) {
    if (!this.initialized || !address) return 0n;
    try {
      return await this.loyaltyToken.balanceOf(address);
    } catch {
      return 0n;
    }
  }

  /**
   * Transfer LYT (Elixir) tokens FROM the admin/treasury wallet to a recipient.
   * Used when a customer swaps ETH/RM into Elixir — the admin sends real
   * on-chain tokens to the customer's MetaMask wallet.
   * @param {string} toAddress    recipient wallet
   * @param {number|string} wholeAmount  amount in whole LYT (not wei)
   * @returns {Promise<string>} transaction hash
   */
  async sendLytFromAdmin(toAddress, wholeAmount) {
    if (!this.initialized || !this.loyaltyToken) {
      throw new Error("Blockchain service not available for Elixir payout");
    }
    if (!ethers.isAddress(toAddress)) {
      throw new Error("Invalid recipient address");
    }
    const amountWei = ethers.parseUnits(wholeAmount.toString(), 18);

    const adminBalance = await this.loyaltyToken.balanceOf(this.adminAddress);
    if (adminBalance < amountWei) {
      throw new Error("Admin Elixir treasury has insufficient balance");
    }

    const tx = await this.loyaltyToken.transfer(toAddress, amountWei);
    const receipt = await tx.wait();
    return receipt.hash;
  }

  /**
   * Verify that a confirmed LYT Transfer moved at least `minWholeAmount`
   * tokens TO `expectedTo`. Used when a customer sends Elixir to the admin
   * (Elixir → ETH/RM swaps) via MetaMask before we release the counter-value.
   */
  async verifyLytTransfer(txHash, expectedTo, minWholeAmount) {
    if (!this.provider || !this.loyaltyToken) {
      throw new Error("Blockchain provider unavailable");
    }
    if (!txHash) throw new Error("Missing transaction hash");

    const receipt = await this.provider.getTransactionReceipt(txHash);
    if (!receipt || receipt.status !== 1) {
      throw new Error("Transaction not confirmed");
    }

    const minWei = ethers.parseUnits(minWholeAmount.toString(), 18);
    const tokenAddr = this.loyaltyTokenAddress.toLowerCase();

    // Scan the receipt logs for a matching Transfer(to=expectedTo, value>=min).
    let matched = false;
    for (const log of receipt.logs) {
      if (log.address.toLowerCase() !== tokenAddr) continue;
      let parsed;
      try {
        parsed = this.loyaltyToken.interface.parseLog(log);
      } catch {
        continue;
      }
      if (parsed && parsed.name === "Transfer") {
        const to = parsed.args[1];
        const value = parsed.args[2];
        if (
          to &&
          to.toLowerCase() === expectedTo.toLowerCase() &&
          value >= minWei
        ) {
          matched = true;
          break;
        }
      }
    }

    if (!matched) {
      throw new Error(
        "No matching Elixir transfer to the platform found in this transaction",
      );
    }
    return true;
  }

  // ── EcommercePayment contract helpers ──────────────────────────────────────

  /**
   * Deployed EcommercePayment contract address.
   */
  get ecommerceAddress() {
    return this.ecommerce ? this.ecommerce.target : null;
  }

  /**
   * Verify a checkout transaction that called the EcommercePayment contract.
   * Confirms the tx is mined, hit our contract, and emitted PaymentCompleted
   * with the expected buyer/seller. Returns the decoded payment details.
   *
   * @param {string} txHash
   * @param {{ buyer?: string, seller?: string }} expected
   */
  async verifyPaymentTx(txHash, expected = {}) {
    if (!this.provider || !this.ecommerce) {
      throw new Error("Blockchain service unavailable");
    }
    if (!txHash) throw new Error("Missing transaction hash");

    const receipt = await this.provider.getTransactionReceipt(txHash);
    if (!receipt || receipt.status !== 1) {
      throw new Error("Transaction not confirmed on-chain");
    }

    const contractAddr = this.ecommerceAddress.toLowerCase();
    let payment = null;

    for (const log of receipt.logs) {
      if (log.address.toLowerCase() !== contractAddr) continue;
      let parsed;
      try {
        parsed = this.ecommerce.interface.parseLog(log);
      } catch {
        continue;
      }
      if (parsed && parsed.name === "PaymentCompleted") {
        payment = {
          orderId: parsed.args.orderId.toString(),
          buyer: parsed.args.buyer,
          seller: parsed.args.seller,
          sellerReceivesWei: parsed.args.sellerReceivesWei.toString(),
          platformFeeWei: parsed.args.platformFeeWei.toString(),
          tokensEarned: parsed.args.tokensEarned.toString(),
          txHash,
          blockNumber: receipt.blockNumber,
        };
        break;
      }
    }

    if (!payment) {
      throw new Error("No PaymentCompleted event found in this transaction");
    }
    if (
      expected.buyer &&
      payment.buyer.toLowerCase() !== expected.buyer.toLowerCase()
    ) {
      throw new Error("Payment was not made from your connected wallet");
    }
    if (
      expected.seller &&
      payment.seller.toLowerCase() !== expected.seller.toLowerCase()
    ) {
      throw new Error("Payment seller does not match the product's seller");
    }

    return payment;
  }

  // ── PurchaseEscrow + PurchaseReceipt helpers ────────────────────────────────

  get escrowAddress() {
    return this.escrow ? this.escrow.target : null;
  }

  get receiptAddress() {
    return this.receipt ? this.receipt.target : null;
  }

  /**
   * Find and decode a single event emitted by a given contract in a tx receipt.
   */
  async _findEvent(contract, txHash, eventName) {
    if (!this.provider || !contract) {
      throw new Error("Blockchain service unavailable");
    }
    if (!txHash) throw new Error("Missing transaction hash");

    const receipt = await this.provider.getTransactionReceipt(txHash);
    if (!receipt || receipt.status !== 1) {
      throw new Error("Transaction not confirmed on-chain");
    }

    const addr = contract.target.toLowerCase();
    for (const log of receipt.logs) {
      if (log.address.toLowerCase() !== addr) continue;
      let parsed;
      try {
        parsed = contract.interface.parseLog(log);
      } catch {
        continue;
      }
      if (parsed && parsed.name === eventName) {
        return { parsed, blockNumber: receipt.blockNumber };
      }
    }
    throw new Error(`No ${eventName} event found in this transaction`);
  }

  /**
   * Verify a buyer's MetaMask createEscrow() call. Confirms the tx hit our
   * escrow contract and (optionally) matches the expected buyer/seller.
   */
  async verifyEscrowCreated(txHash, expected = {}) {
    if (!this.escrow) throw new Error("Escrow contract not available");
    const { parsed, blockNumber } = await this._findEvent(
      this.escrow,
      txHash,
      "EscrowCreated",
    );
    const result = {
      escrowId: parsed.args.escrowId.toString(),
      buyer: parsed.args.buyer,
      seller: parsed.args.seller,
      asset: Number(parsed.args.asset), // 0 = ETH, 1 = TOKEN
      amount: parsed.args.amount.toString(),
      productRef: parsed.args.productRef,
      txHash,
      blockNumber,
    };
    if (
      expected.buyer &&
      result.buyer.toLowerCase() !== expected.buyer.toLowerCase()
    ) {
      throw new Error("Escrow was not funded from your connected wallet");
    }
    if (
      expected.seller &&
      result.seller.toLowerCase() !== expected.seller.toLowerCase()
    ) {
      throw new Error("Escrow seller does not match the product's seller");
    }
    return result;
  }

  /**
   * Verify an EscrowReleased event (delivery confirmed / auto-released).
   */
  async verifyEscrowReleased(txHash, expected = {}) {
    if (!this.escrow) throw new Error("Escrow contract not available");
    const { parsed, blockNumber } = await this._findEvent(
      this.escrow,
      txHash,
      "EscrowReleased",
    );
    const result = {
      escrowId: parsed.args.escrowId.toString(),
      buyer: parsed.args.buyer,
      seller: parsed.args.seller,
      asset: Number(parsed.args.asset),
      sellerReceivesWei: parsed.args.sellerReceives.toString(),
      platformFeeWei: parsed.args.platformFee.toString(),
      tokensEarned: parsed.args.tokensEarned.toString(),
      receiptTokenId: parsed.args.receiptTokenId.toString(),
      autoReleased: parsed.args.autoReleased,
      txHash,
      blockNumber,
    };
    if (
      expected.escrowId &&
      result.escrowId !== String(expected.escrowId)
    ) {
      throw new Error("Release does not match this order's escrow");
    }
    return result;
  }

  /**
   * Verify an EscrowDisputed event.
   */
  async verifyEscrowDisputed(txHash, expected = {}) {
    if (!this.escrow) throw new Error("Escrow contract not available");
    const { parsed } = await this._findEvent(
      this.escrow,
      txHash,
      "EscrowDisputed",
    );
    const result = {
      escrowId: parsed.args.escrowId.toString(),
      buyer: parsed.args.buyer,
      seller: parsed.args.seller,
      txHash,
    };
    if (expected.escrowId && result.escrowId !== String(expected.escrowId)) {
      throw new Error("Dispute does not match this order's escrow");
    }
    return result;
  }

  /**
   * Admin resolves a disputed escrow: refund the buyer or release to the
   * seller. Sent from the platform admin wallet (contract owner).
   */
  async resolveEscrowDispute(escrowId, refundBuyer) {
    if (!this.escrow) throw new Error("Escrow contract not available");
    const tx = await this.escrow.resolveDispute(BigInt(escrowId), !!refundBuyer);
    const receipt = await tx.wait();

    // Decode the resulting outcome for the caller.
    let released = null;
    let refunded = null;
    for (const log of receipt.logs) {
      if (log.address.toLowerCase() !== this.escrow.target.toLowerCase()) continue;
      let parsed;
      try {
        parsed = this.escrow.interface.parseLog(log);
      } catch {
        continue;
      }
      if (parsed && parsed.name === "EscrowReleased") {
        released = {
          sellerReceivesWei: parsed.args.sellerReceives.toString(),
          receiptTokenId: parsed.args.receiptTokenId.toString(),
        };
      }
      if (parsed && parsed.name === "EscrowRefunded") {
        refunded = { amountWei: parsed.args.amount.toString() };
      }
    }
    return { txHash: receipt.hash, released, refunded };
  }

  /**
   * Mint an NFT purchase receipt from the admin (owner) wallet. Used for
   * non-escrow orders (escrow orders mint their receipt on-chain at release).
   * Returns { tokenId, txHash } or null when receipts aren't available.
   */
  async mintReceiptFromAdmin({ to, orderRef, productRef, seller, pricePaidWei }) {
    if (!this.receipt) return null;
    if (!ethers.isAddress(to)) return null;

    const tx = await this.receipt.mintReceipt(
      to,
      String(orderRef),
      String(productRef),
      ethers.isAddress(seller) ? seller : ethers.ZeroAddress,
      BigInt(pricePaidWei || 0),
    );
    const receipt = await tx.wait();

    let tokenId = null;
    for (const log of receipt.logs) {
      if (log.address.toLowerCase() !== this.receipt.target.toLowerCase()) continue;
      let parsed;
      try {
        parsed = this.receipt.interface.parseLog(log);
      } catch {
        continue;
      }
      if (parsed && parsed.name === "ReceiptMinted") {
        tokenId = parsed.args.tokenId.toString();
        break;
      }
    }
    return { tokenId, txHash: receipt.hash };
  }

  /**
   * Read a receipt's on-chain record.
   */
  async getReceipt(tokenId) {
    if (!this.receipt) throw new Error("Receipt contract not available");
    const r = await this.receipt.getReceipt(BigInt(tokenId));
    return {
      tokenId: String(tokenId),
      orderRef: r.orderRef,
      productRef: r.productRef,
      buyer: r.buyer,
      seller: r.seller,
      pricePaidWei: r.pricePaidWei.toString(),
      pricePaidEth: ethers.formatEther(r.pricePaidWei),
      issuedAt: Number(r.issuedAt),
    };
  }

  /**
   * List every receipt token id owned by an address.
   */
  async getReceiptsOf(owner) {
    if (!this.receipt || !ethers.isAddress(owner)) return [];
    const ids = await this.receipt.receiptsOf(owner);
    return ids.map((id) => id.toString());
  }
}

// Singleton instance
const blockchainService = new BlockchainService();
module.exports = blockchainService;
