import React from "react";

export const css = {
  shell: {
    minHeight: "100vh",
    display: "grid",
    gridTemplateColumns: "270px minmax(0, 1fr)",
    background:
      "linear-gradient(135deg, #060d1a 0%, #0c1524 50%, #0f1e35 100%)",
    color: "#e2e8f0",
    fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
  },
  loadingScreen: {
    minHeight: "100vh",
    display: "grid",
    placeItems: "center",
    justifyItems: "center",
    background: "linear-gradient(135deg, #060d1a, #0c1524)",
    color: "#e2e8f0",
  },
  loadingSpinner: {
    width: 40,
    height: 40,
    border: "3px solid rgba(56,189,248,0.2)",
    borderTopColor: "#38bdf8",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  loadingInline: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    color: "#64748b",
    padding: "12px 0",
  },
  loadingSpinnerSm: {
    width: 18,
    height: 18,
    border: "2px solid rgba(56,189,248,0.2)",
    borderTopColor: "#38bdf8",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
    flexShrink: 0,
  },
  sidebar: {
    padding: 24,
    borderRight: "1px solid rgba(148, 163, 184, 0.1)",
    background: "rgba(6, 13, 26, 0.85)",
    backdropFilter: "blur(20px)",
    display: "flex",
    flexDirection: "column",
    gap: 18,
    position: "sticky",
    top: 0,
    height: "100vh",
    overflowY: "auto",
  },
  brandBlock: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    paddingBottom: 8,
    borderBottom: "1px solid rgba(148,163,184,0.08)",
  },
  brandMark: {
    width: 48,
    height: 48,
    borderRadius: 14,
    display: "grid",
    placeItems: "center",
    background: "linear-gradient(135deg, #0ea5e9, #818cf8)",
    color: "#060d1a",
    fontWeight: 800,
    flexShrink: 0,
  },
  brandKicker: {
    margin: 0,
    fontSize: 10,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    color: "#475569",
  },
  brandTitle: {
    margin: "4px 0 0",
    fontSize: 20,
    fontWeight: 800,
    background: "linear-gradient(135deg, #38bdf8, #818cf8)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  nav: { display: "grid", gap: 6 },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid transparent",
    background: "transparent",
    color: "#64748b",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
    textAlign: "left",
    transition: "all 0.15s",
    textDecoration: "none",
  },
  navItemHover: {
    background: "rgba(15, 23, 42, 0.5)",
    color: "#94a3b8",
    border: "1px solid rgba(148,163,184,0.1)",
  },
  navItemActive: {
    background:
      "linear-gradient(135deg, rgba(14,165,233,0.15), rgba(129,140,248,0.2))",
    color: "#f8fafc",
    border: "1px solid rgba(125, 211, 252, 0.25)",
    fontWeight: 700,
  },
  navIcon: { fontSize: 16, flexShrink: 0 },
  snapshotCard: {
    marginTop: "auto",
    padding: "14px 16px",
    borderRadius: 16,
    background: "rgba(15, 23, 42, 0.7)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
  },
  snapshotLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1.4,
    color: "#475569",
  },
  snapRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "7px 0",
    borderBottom: "1px solid rgba(148,163,184,0.07)",
  },
  snapLeft: { display: "flex", alignItems: "center", gap: 8 },
  snapIcon: { fontSize: 13, color: "#64748b", fontWeight: 700 },
  snapLabel: { fontSize: 12, color: "#64748b" },
  snapValue: { fontSize: 13, color: "#cbd5e1" },
  logoutBtn: {
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid rgba(248, 113, 113, 0.18)",
    background: "rgba(248, 113, 113, 0.06)",
    color: "#f87171",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: 13,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  main: { padding: "28px 32px", overflowY: "auto" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 20,
    marginBottom: 28,
    flexWrap: "wrap",
  },
  headerKicker: {
    margin: 0,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1.6,
    color: "#475569",
  },
  headerTitle: {
    margin: "8px 0 0",
    fontSize: "clamp(1.6rem, 3vw, 2.4rem)",
    fontWeight: 800,
    lineHeight: 1.1,
    color: "#f8fafc",
  },
  headerName: {
    background: "linear-gradient(135deg, #38bdf8, #818cf8)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  profileChip: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 16px",
    borderRadius: 16,
    background: "rgba(15, 23, 42, 0.7)",
    border: "1px solid rgba(148, 163, 184, 0.12)",
    flexShrink: 0,
  },
  profileAvatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #0ea5e9, #818cf8)",
    display: "grid",
    placeItems: "center",
    fontWeight: 800,
    fontSize: 16,
    color: "#060d1a",
    flexShrink: 0,
  },
  chipRole: {
    margin: 0,
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#475569",
  },
  chipAddress: {
    margin: "3px 0 0",
    fontSize: 12,
    color: "#94a3b8",
    fontWeight: 600,
  },
  sectionCard: {
    padding: 24,
    borderRadius: 22,
    background: "rgba(12, 21, 36, 0.7)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
    boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
    marginBottom: 24,
    backdropFilter: "blur(12px)",
  },
  sectionHead: { marginBottom: 20 },
  sectionLabel: {
    margin: 0,
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1.6,
    color: "#475569",
  },
  sectionTitle: {
    margin: "6px 0 0",
    fontSize: 26,
    fontWeight: 800,
    color: "#f8fafc",
  },
  catRow: { display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 20 },
  catBtn: {
    padding: "8px 16px",
    borderRadius: 999,
    border: "1px solid rgba(148, 163, 184, 0.12)",
    background: "rgba(15, 23, 42, 0.6)",
    color: "#64748b",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    transition: "all 0.15s",
  },
  catBtnActive: {
    background:
      "linear-gradient(135deg, rgba(14,165,233,0.2), rgba(129,140,248,0.2))",
    color: "#f8fafc",
    borderColor: "rgba(125, 211, 252, 0.4)",
  },
  productGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 14,
    marginBottom: 20,
  },
  productCard: {
    textAlign: "left",
    padding: 18,
    borderRadius: 18,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
    color: "#e2e8f0",
    cursor: "pointer",
    display: "grid",
    gap: 10,
    transition: "all 0.2s",
    position: "relative",
  },
  productCardActive: {},
  productTopRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pill: {
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "capitalize",
  },
  stockBadge: { fontSize: 11, color: "#64748b", fontWeight: 600 },
  productName: { margin: 0, fontSize: 17, fontWeight: 800, color: "#f1f5f9" },
  productDesc: { margin: 0, fontSize: 12, color: "#64748b", lineHeight: 1.5 },
  productPrices: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 8,
    paddingTop: 8,
    borderTop: "1px solid rgba(148,163,184,0.08)",
  },
  priceTag: { display: "grid", gap: 2 },
  priceTagLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "#475569",
  },
  priceTagValue: { fontSize: 13, fontWeight: 700, color: "#e2e8f0" },
  selectedBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    padding: "3px 8px",
    borderRadius: 999,
    background: "rgba(56,189,248,0.15)",
    color: "#38bdf8",
    fontSize: 10,
    fontWeight: 700,
  },
  checkoutPanel: {
    marginTop: 8,
    paddingTop: 20,
    borderTop: "1px solid rgba(148, 163, 184, 0.1)",
  },
  checkoutPanelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 18,
  },
  deselectBtn: {
    padding: "6px 12px",
    borderRadius: 10,
    border: "1px solid rgba(148,163,184,0.15)",
    background: "transparent",
    color: "#64748b",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 700,
  },
  balanceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0,1fr))",
    gap: 14,
    marginBottom: 20,
  },
  balanceCardBase: {
    padding: "18px 20px",
    borderRadius: 20,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid",
    display: "grid",
    gap: 6,
  },
  balanceCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    display: "grid",
    placeItems: "center",
    fontSize: 15,
    fontWeight: 800,
    justifySelf: "start",
  },
  balanceCardLabel: {
    margin: 0,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#475569",
  },
  balanceCardValue: { margin: 0, fontSize: 22, fontWeight: 800 },
  balanceCardSub: { margin: 0, fontSize: 12, color: "#475569" },
  walletNavBar: {
    display: "flex",
    gap: 6,
    padding: 6,
    borderRadius: 16,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
    marginBottom: 16,
  },
  walletNavBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid transparent",
    background: "transparent",
    color: "#64748b",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 700,
    transition: "all 0.15s",
  },
  walletNavBtnActive: {
    background:
      "linear-gradient(135deg, rgba(14,165,233,0.18), rgba(129,140,248,0.22))",
    color: "#f8fafc",
    border: "1px solid rgba(125, 211, 252, 0.3)",
  },
  swapLayout: {
    display: "grid",
    gridTemplateColumns: "1.4fr 1fr",
    gap: 16,
    alignItems: "start",
  },
  priceTickerPanel: {
    padding: "20px 22px",
    borderRadius: 20,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
    display: "grid",
    gap: 14,
    alignSelf: "start",
  },
  priceTickerTitle: {
    margin: 0,
    fontSize: 13,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#475569",
  },
  priceTickerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 16px",
    borderRadius: 14,
    background: "rgba(15, 23, 42, 0.6)",
    border: "1px solid rgba(148,163,184,0.08)",
  },
  priceTickerLeft: { display: "flex", alignItems: "center", gap: 10 },
  priceTickerIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    display: "grid",
    placeItems: "center",
    fontSize: 14,
    fontWeight: 800,
  },
  priceTickerPair: { margin: 0, fontSize: 13, fontWeight: 700, color: "#e2e8f0" },
  priceTickerSub: { margin: "2px 0 0", fontSize: 11, color: "#475569" },
  priceTickerValue: { margin: 0, fontSize: 16, fontWeight: 800, color: "#f8fafc" },
  priceTickerChange: { margin: "2px 0 0", fontSize: 11, fontWeight: 700 },
  swapWidget: {
    padding: "20px 22px",
    borderRadius: 20,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
    marginBottom: 16,
    display: "grid",
    gap: 16,
  },
  swapWidgetHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  swapTitle: { margin: 0, fontSize: 18, fontWeight: 800, color: "#f1f5f9" },
  swapRate: { margin: 0, fontSize: 12, color: "#475569" },
  swapDirectionRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  dirBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(148,163,184,0.12)",
    background: "rgba(15,23,42,0.5)",
    color: "#64748b",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 700,
  },
  dirBtnActive: {
    background: "rgba(14,165,233,0.1)",
    border: "1px solid rgba(14,165,233,0.35)",
    boxShadow: "0 0 12px rgba(14,165,233,0.15)",
  },
  swapArrow: { color: "#475569", fontSize: 16 },
  swapInputRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: 12,
    alignItems: "end",
  },
  swapInputGroup: { display: "grid", gap: 8 },
  swapPreviewBox: {
    padding: "12px 16px",
    borderRadius: 14,
    background: "rgba(14,165,233,0.08)",
    border: "1px solid rgba(14,165,233,0.2)",
    textAlign: "center",
    minWidth: 120,
  },
  swapPreviewLabel: {
    margin: 0,
    fontSize: 10,
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  swapPreviewValue: {
    margin: "4px 0 0",
    fontSize: 16,
    fontWeight: 800,
    color: "#38bdf8",
  },
  swapBtn: {
    padding: "13px 18px",
    borderRadius: 14,
    border: "none",
    background: "linear-gradient(135deg, #0ea5e9, #818cf8)",
    color: "#060d1a",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 14,
  },
  walletActionsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 14,
  },
  walletActionCard: {
    padding: "18px 20px",
    borderRadius: 18,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
    display: "grid",
    gap: 10,
  },
  walletActionTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 800,
    color: "#f1f5f9",
  },
  inputLabel: { fontSize: 12, color: "#64748b", fontWeight: 600 },
  inputField: {
    width: "100%",
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid rgba(148, 163, 184, 0.15)",
    background: "rgba(15, 23, 42, 0.8)",
    color: "#e2e8f0",
    fontSize: 14,
    boxSizing: "border-box",
    outline: "none",
    fontFamily: "inherit",
  },
  actionBtn: {
    padding: "12px 14px",
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg, #10b981, #34d399)",
    color: "#060d1a",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 14,
  },
  walletToast: {
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid",
    fontSize: 14,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  splitGrid: { display: "grid", gridTemplateColumns: "1.3fr 0.7fr", gap: 16 },
  panel: {
    borderRadius: 18,
    padding: 18,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid rgba(148, 163, 184, 0.1)",
  },
  inlineRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  selectField: {
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid rgba(148,163,184,0.15)",
    background: "rgba(15,23,42,0.9)",
    color: "#e2e8f0",
    fontSize: 13,
    minWidth: 200,
    outline: "none",
  },
  timeline: { display: "grid", gap: 0, marginBottom: 16 },
  timelineRow: {
    display: "grid",
    gridTemplateColumns: "18px 2px 1fr",
    gap: "0 10px",
    alignItems: "start",
    position: "relative",
  },
  dot: {
    width: 14,
    height: 14,
    borderRadius: "50%",
    marginTop: 2,
    background: "rgba(100, 116, 139, 0.3)",
    border: "2px solid rgba(100,116,139,0.4)",
    gridColumn: 1,
    flexShrink: 0,
    position: "relative",
    zIndex: 1,
  },
  dotActive: {
    background: "linear-gradient(135deg, #38bdf8, #818cf8)",
    borderColor: "transparent",
    boxShadow: "0 0 0 4px rgba(56,189,248,0.12)",
  },
  timelineConnector: (done, hasNext) => ({
    gridColumn: 2,
    gridRow: "1 / 3",
    width: 2,
    background:
      done && hasNext ? "rgba(56,189,248,0.4)" : "rgba(100,116,139,0.15)",
    minHeight: 40,
    alignSelf: "stretch",
  }),
  timelineText: { gridColumn: 3, paddingBottom: 14 },
  timelineStepName: { margin: 0, fontSize: 14, fontWeight: 700 },
  timelineStatus: { margin: "3px 0 0", fontSize: 12, color: "#475569" },
  summaryCard: {
    padding: 16,
    borderRadius: 16,
    background: "rgba(15, 23, 42, 0.5)",
    border: "1px solid rgba(148,163,184,0.1)",
  },
  subTitle: {
    margin: "0 0 14px",
    fontSize: 16,
    fontWeight: 800,
    color: "#f1f5f9",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 10,
    marginBottom: 12,
  },
  summaryItem: {
    padding: "10px 12px",
    borderRadius: 12,
    background: "rgba(8, 15, 28, 0.5)",
    border: "1px solid rgba(148,163,184,0.08)",
    display: "grid",
    gap: 4,
  },
  summaryLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "#475569",
  },
  summaryValue: { fontSize: 13, color: "#e2e8f0", wordBreak: "break-word" },
  txBox: { display: "grid", gap: 6, marginTop: 12 },
  txLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "#475569",
  },
  txCode: {
    display: "block",
    padding: "8px 12px",
    borderRadius: 10,
    background: "rgba(6, 13, 26, 0.7)",
    color: "#7dd3fc",
    fontSize: 11,
    wordBreak: "break-all",
    border: "1px solid rgba(125,211,252,0.12)",
  },
  elixirEarned: {
    marginTop: 12,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 12px",
    borderRadius: 12,
    background: "rgba(56, 189, 248, 0.06)",
    border: "1px solid rgba(56,189,248,0.12)",
    fontSize: 14,
  },
  logCard: { display: "grid", gap: 10 },
  logItem: {
    display: "grid",
    gridTemplateColumns: "100px 1fr",
    gap: 8,
    padding: "8px 0",
    borderBottom: "1px solid rgba(148,163,184,0.07)",
    fontSize: 13,
  },
  logLabel: {
    color: "#475569",
    fontWeight: 700,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    alignSelf: "start",
    paddingTop: 1,
  },
  logValue: { color: "#cbd5e1", wordBreak: "break-word" },
  historyList: { display: "grid", gap: 12 },
  historyItem: {
    padding: 18,
    borderRadius: 18,
    background: "rgba(8, 15, 28, 0.6)",
    border: "1px solid rgba(148,163,184,0.1)",
    display: "grid",
    gap: 14,
  },
  historyTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  historyLeft: { display: "flex", alignItems: "center", gap: 12 },
  historyIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    background:
      "linear-gradient(135deg, rgba(14,165,233,0.2), rgba(129,140,248,0.2))",
    border: "1px solid rgba(125,211,252,0.15)",
    display: "grid",
    placeItems: "center",
    fontWeight: 800,
    fontSize: 16,
    color: "#7dd3fc",
  },
  historyName: { margin: 0, fontSize: 15, fontWeight: 800, color: "#f1f5f9" },
  historyMeta: { margin: "3px 0 0", fontSize: 12, color: "#475569" },
  historyRight: { display: "flex", alignItems: "center", gap: 10 },
  statusBadge: {
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "capitalize",
    border: "1px solid",
  },
  viewBtn: {
    padding: "6px 12px",
    borderRadius: 10,
    border: "none",
    background: "transparent",
    color: "#38bdf8",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 13,
  },
  emptyState: {
    textAlign: "center",
    padding: "48px 24px",
    display: "grid",
    placeItems: "center",
    gap: 12,
  },
  emptyIcon: { fontSize: 48 },
  emptyTitle: { margin: 0, fontSize: 20, fontWeight: 800, color: "#f1f5f9" },
  shopNowBtn: {
    padding: "12px 24px",
    borderRadius: 14,
    border: "none",
    background: "linear-gradient(135deg, #0ea5e9, #818cf8)",
    color: "#060d1a",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 14,
    marginTop: 4,
  },
  profileGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 16,
  },
  muted: { color: "#475569", fontSize: 14 },
  helperText: { color: "#475569", fontSize: 13, margin: "6px 0" },
};

export function Section({ label, title, children }) {
  return (
    <section style={css.sectionCard}>
      <div style={css.sectionHead}>
        <p style={css.sectionLabel}>{label}</p>
        <h3 style={css.sectionTitle}>{title}</h3>
      </div>
      {children}
    </section>
  );
}

export function SnapRow({ icon, label, value }) {
  return (
    <div style={css.snapRow}>
      <div style={css.snapLeft}>
        <span style={css.snapIcon}>{icon}</span>
        <span style={css.snapLabel}>{label}</span>
      </div>
      <strong style={css.snapValue}>{value}</strong>
    </div>
  );
}

export function BalanceCard({ icon, label, value, sub, color }) {
  return (
    <div
      style={{
        ...css.balanceCardBase,
        borderColor: `${color}33`,
        boxShadow: `0 4px 24px ${color}18`,
      }}
    >
      <div style={{ ...css.balanceCardIcon, background: `${color}20`, color }}>
        {icon}
      </div>
      <p style={css.balanceCardLabel}>{label}</p>
      <p style={{ ...css.balanceCardValue, color }}>{value}</p>
      <p style={css.balanceCardSub}>{sub}</p>
    </div>
  );
}

export function SummaryItem({ label, value }) {
  return (
    <div style={css.summaryItem}>
      <span style={css.summaryLabel}>{label}</span>
      <strong style={css.summaryValue}>{value}</strong>
    </div>
  );
}

export function LogItem({ label, value }) {
  return (
    <div style={css.logItem}>
      <span style={css.logLabel}>{label}</span>
      <span style={css.logValue}>{value}</span>
    </div>
  );
}
