"""
Test case tables for the Elixir Commerce blockchain e-commerce platform.

Format mirrors the sample: TCNO | User Input | System Action | Expected Output
| Actual Output | Result, with a caption below each table. Actual Output and
Result are left blank for the tester to fill in during execution.

Content is derived directly from the Basic / Alternative / Exception flows in
docs/usecase-specifications.md, so every test case traces back to a specific
use case (UC-C-xx / UC-M-xx / UC-A-xx) and, through it, to the real backend
route it exercises.
"""

GROUPS = [
    # ================================================================
    # A. CUSTOMER
    # ================================================================
    {
        "actor": "Customer",
        "usecase": "UC-C-01 Register",
        "table_no": 1,
        "title": "Register Page Test Case",
        "cases": [
            ("RG01", "Fill name, email, password; select role Customer; submit",
             "System validates fields and creates a User + CustomerWallet row",
             "Account created; JWT returned; user redirected to /shop"),
            ("RG02", "Fill name, email, password; select role Merchant; submit",
             "System creates a User row with role merchant (no CustomerWallet)",
             "Account created; user redirected to Seller Portal"),
            ("RG03", "Submit form with email already registered",
             "System checks for a duplicate email before creating the row",
             "HTTP 409 \"Email already registered\"; no new row created"),
            ("RG04", "Submit form with the Name field left empty",
             "System validates required fields before creating the row",
             "HTTP 400 \"Name, email and password are required\""),
            ("RG05", "Click \"Back to login\" link",
             "User is returned to the Login page",
             "User is directed to the Login page"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-02 Login",
        "table_no": 2,
        "title": "Login Page Test Case",
        "cases": [
            ("LG01", "Enter a registered email and correct password; click Sign In",
             "System verifies the bcrypt password hash and signs a JWT",
             "User is authenticated and redirected to the role's dashboard"),
            ("LG02", "Enter a registered email with an incorrect password",
             "System compares the password hash and rejects the mismatch",
             "HTTP 401 \"Invalid credentials\"; user remains on Login page"),
            ("LG03", "Enter an email that is not registered",
             "System looks up the user by email and finds none",
             "HTTP 401 \"Invalid credentials\" (same message as LG02)"),
            ("LG04", "Submit the form with the Password field empty",
             "System validates required fields",
             "HTTP 400; user remains on Login page"),
            ("LG05", "Click \"Create an account now\" link",
             "User is directed to the Register page",
             "User is directed to the Register page"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-03 Connect MetaMask Wallet",
        "table_no": 3,
        "title": "Connect MetaMask Wallet Test Case",
        "cases": [
            ("MM01", "Click \"Connect MetaMask\" and approve the popup",
             "MetaMask returns the address; backend links it via /api/auth/link-metamask",
             "Wallet chip shows the address and live ETH balance; ETH/Elixir payments unlock"),
            ("MM02", "Click \"Connect MetaMask\" and reject the popup",
             "MetaMask cancels the connection request",
             "No wallet is linked; the Connect MetaMask button remains visible"),
            ("MM03", "Connect a MetaMask address already linked to another account",
             "Backend detects the address is bound to a different user",
             "HTTP 409 ADDRESS_IN_USE; frontend disconnects the wallet"),
            ("MM04", "Connect a second MetaMask address while one is already linked to this account",
             "Backend detects the account already has a different linked address",
             "HTTP 409 ALREADY_BOUND_TO_USER; frontend disconnects the new wallet"),
            ("MM05", "Connect the same MetaMask address that is already linked to this account",
             "Backend finds the address already matches this account",
             "Request succeeds with no changes; UI shows \"already linked\""),
            ("MM06", "Click the red \u2715 disconnect button on the wallet chip",
             "Frontend disconnects the MetaMask session (account link on the backend is unaffected)",
             "Wallet chip is replaced by the \"Connect MetaMask\" button"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-04 Browse / Search Products",
        "table_no": 4,
        "title": "Shop Page Test Case",
        "cases": [
            ("SP01", "Open the Shop page with no filters applied",
             "Frontend calls GET /api/products and renders active products",
             "Product grid displays all active products"),
            ("SP02", "Click the \"Clothes\" category pill",
             "Frontend calls GET /api/products?category=clothes",
             "Product grid updates to show only clothes-category products"),
            ("SP03", "Type \"hoodie\" into the search box",
             "Frontend calls GET /api/products?search=hoodie with a case-insensitive LIKE match",
             "Product grid filters to products whose name contains \"hoodie\""),
            ("SP04", "Click \"by {merchant name}\" on a product card",
             "Frontend switches to single-seller mode, filtering by merchantId",
             "Product grid shows only that seller's products; store banner appears"),
            ("SP05", "Click a product card to view its detail",
             "Frontend calls GET /api/products/:id",
             "Product detail view is displayed with full description and price"),
            ("SP06", "Request a product id that does not exist",
             "Backend cannot find a matching Product row",
             "HTTP 404 returned; frontend shows a not-found state"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-05 Manage Cart",
        "table_no": 5,
        "title": "Cart Management Test Case",
        "cases": [
            ("CT01", "Click \"Add to Cart\" on an in-stock product",
             "Frontend calls POST /api/cart; backend creates or increments the cart row",
             "Item appears in the cart; button briefly shows \"Added \u2713\""),
            ("CT02", "Click \"+\" to increase a cart item's quantity beyond available stock",
             "Backend caps the requested quantity at the product's stock level",
             "Quantity is capped at stock; no error is raised"),
            ("CT03", "Click \"\u2212\" to reduce a cart item's quantity",
             "Frontend calls PUT /api/cart/:id with the reduced quantity",
             "Cart line item quantity decreases and subtotal updates"),
            ("CT04", "Click the red \u2715 remove button on a cart item",
             "Frontend calls DELETE /api/cart/:id",
             "Item is removed from the cart; subtotal recalculates"),
            ("CT05", "Add a product from a second seller while items from a first seller are already in the cart",
             "Cart groups items into separate per-seller sections",
             "Cart displays two store sections, each with its own subtotal and checkout button"),
            ("CT06", "Open the Cart page with no items added",
             "Frontend detects an empty cart response",
             "Empty state is shown: \"Your cart is empty\""),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-06a Checkout with ETH",
        "table_no": 6,
        "title": "Checkout \u2014 ETH Payment Test Case",
        "cases": [
            ("CE01", "Select ETH payment mode with MetaMask connected and sufficient balance; confirm",
             "MetaMask calls payWithETH; backend verifies the PaymentCompleted event",
             "Order created with status completed; seller paid; buyer earns Elixir reward"),
            ("CE02", "Select ETH payment mode while MetaMask is not connected",
             "System blocks the crypto payment options",
             "HTTP 400 \"Connect your MetaMask wallet to pay with ETH\"; ETH card is locked"),
            ("CE03", "Confirm ETH payment with insufficient ETH balance in MetaMask",
             "MetaMask rejects the transaction before it is broadcast",
             "Transaction is not sent; user remains on the Checkout page with an error"),
            ("CE04", "Submit a manipulated/unmined txHash to the backend",
             "Backend re-reads the transaction receipt and fails to verify the PaymentCompleted event",
             "HTTP 400 with the verification error message; no Order is created"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-06b Checkout with Elixir",
        "table_no": 7,
        "title": "Checkout \u2014 Elixir Payment Test Case",
        "cases": [
            ("CX01", "Select Elixir payment mode with sufficient Elixir balance; confirm",
             "MetaMask calls payWithTokens; backend verifies the PaymentCompleted event",
             "Order created with paymentMode TOKEN_ONLY; seller paid ETH from contract reserve"),
            ("CX02", "Select Elixir payment mode with insufficient Elixir balance",
             "Frontend shows an insufficient-balance warning before submission",
             "\"Insufficient Elixir balance ({n} available)\" warning shown; payment blocked"),
            ("CX03", "Select Elixir payment mode while MetaMask is not connected",
             "System blocks the crypto payment options",
             "Elixir card is locked; MetaMask connect prompt is shown"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-06c Checkout with ETH Escrow",
        "table_no": 8,
        "title": "Checkout \u2014 ETH Escrow Test Case",
        "cases": [
            ("CS01", "Select ETH Escrow with a multi-product basket; confirm",
             "MetaMask calls createEscrow; backend verifies EscrowCreated and checks the escrowed amount",
             "Multi-item Order created with escrowStatus funded; stock decremented; cart cleared"),
            ("CS02", "Confirm ETH Escrow where the escrowed amount is less than the basket total",
             "Backend checks the escrowed amount covers at least 99% of the basket total",
             "HTTP 400 \"Escrowed ETH is less than the order total\"; no Order created"),
            ("CS03", "Confirm ETH Escrow while MetaMask is not connected",
             "System blocks the escrow payment option",
             "HTTP 400; ETH Escrow option is locked in the UI"),
            ("CS04", "Confirm ETH Escrow with a basket containing items from two sellers",
             "Frontend splits the basket into one escrow checkout per seller",
             "Two separate escrow orders are created, one per seller"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-06d Checkout with Elixir Escrow",
        "table_no": 9,
        "title": "Checkout \u2014 Elixir Escrow Test Case",
        "cases": [
            ("CZ01", "Select Elixir Escrow; approve the token spend, then confirm the escrow lock",
             "MetaMask requests an approve signature, then a createTokenEscrow signature",
             "Two MetaMask prompts appear in sequence; Order created with escrowStatus funded"),
            ("CZ02", "Confirm Elixir Escrow where the escrowed Elixir is less than the basket total",
             "Backend checks the escrowed Elixir covers at least 99% of the basket total",
             "HTTP 400; no Order created"),
            ("CZ03", "Cancel the second MetaMask signature (the escrow lock) after approving the token spend",
             "Frontend detects the second signature was never returned",
             "Checkout is not completed; approved allowance remains but no funds are escrowed"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-06e Checkout with RM",
        "table_no": 10,
        "title": "Checkout \u2014 RM Payment Test Case",
        "cases": [
            ("CR01", "Select RM payment mode with sufficient RM balance; confirm",
             "Backend opens a MySQL transaction, deducts RM, and creates the Order",
             "Order created immediately with status completed; no MetaMask prompt required"),
            ("CR02", "Select RM payment mode with insufficient RM balance",
             "Backend checks the wallet's RM balance against the basket total",
             "HTTP 400 \"Insufficient RM balance. Need RM X, have RM Y.\"; transaction rolled back"),
            ("CR03", "Confirm RM payment while MetaMask is disconnected",
             "System allows the RM checkout to proceed without a wallet check",
             "Order completes successfully with no MetaMask requirement"),
            ("CR04", "Leave the Delivery Address field empty and click Confirm & Pay",
             "Frontend/backend validates that a delivery address is required",
             "Form does not submit, or backend rejects the request until an address is provided"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-07 Track Order Status / History",
        "table_no": 11,
        "title": "Track Order & History Test Case",
        "cases": [
            ("TO01", "Open the Track Order page with at least one order placed",
             "Frontend calls GET /api/orders/my and renders the order list with stage badges",
             "Orders are split into On-going and Completed tabs with correct counts"),
            ("TO02", "Click an order row to expand it",
             "Frontend renders the 5-step delivery timeline and order summary",
             "Timeline, summary grid, transaction hash and Elixir earned are displayed"),
            ("TO03", "Open the History page and click the \"Swaps\" filter pill",
             "Frontend filters the merged order/transaction feed to type SWAP only",
             "Feed shows only swap transactions"),
            ("TO04", "Open the History page with no activity recorded",
             "Frontend detects an empty feed response",
             "Empty state is shown: \"No activity yet\""),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-08 Confirm Delivery",
        "table_no": 12,
        "title": "Confirm Delivery Test Case",
        "cases": [
            ("CD01", "Click \"Confirm Delivery & Release\" on a funded escrow order",
             "MetaMask calls confirmDelivery; backend verifies EscrowReleased and updates the order",
             "escrowStatus becomes released; fulfillmentStage set to 4; NFT receipt minted"),
            ("CD02", "Click \"Confirm Delivery & Release\" while MetaMask is disconnected",
             "System shows a Connect MetaMask prompt instead of the action buttons",
             "\"Connect MetaMask to manage escrow\" button is shown; action is blocked"),
            ("CD03", "Submit a txHash that fails on-chain event verification",
             "Backend cannot decode an EscrowReleased event from the receipt",
             "Order state remains unchanged; delivery is not marked confirmed"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-09 Raise Dispute",
        "table_no": 13,
        "title": "Raise Dispute Test Case",
        "cases": [
            ("RD01", "Click \"Raise Dispute\" on a funded escrow order",
             "MetaMask calls raiseDispute; backend verifies EscrowDisputed and updates escrowStatus",
             "Order's escrowStatus becomes disputed; order appears in the Admin Disputes queue"),
            ("RD02", "Click \"Raise Dispute\" on an order that is not in a funded escrow state",
             "System only exposes the dispute action for funded escrow orders",
             "Raise Dispute button is not shown for that order"),
            ("RD03", "Click \"Raise Dispute\" while MetaMask is disconnected",
             "System shows a Connect MetaMask prompt instead of the action buttons",
             "Dispute action is blocked until MetaMask is connected"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-10a Stake Elixir",
        "table_no": 14,
        "title": "Stake Elixir Test Case",
        "cases": [
            ("ST01", "Select the 90-day tier, enter a valid Elixir amount, click Stake",
             "MetaMask transfers Elixir to the treasury; backend verifies the transfer and creates a StakePosition",
             "New active staking position appears with tierDays 90 and locked-in APY 14%"),
            ("ST02", "Click \"MAX\" then Stake",
             "Frontend fills the input with the full available Elixir balance before submitting",
             "Amount field shows the full balance; stake is created for that full amount"),
            ("ST03", "Enter a stake amount greater than the available Elixir balance",
             "MetaMask rejects the transfer due to insufficient balance",
             "Transaction fails before submission; no StakePosition is created"),
            ("ST04", "Attempt to stake while MetaMask is disconnected",
             "System blocks the staking action",
             "Stake button is disabled or a Connect MetaMask prompt is shown"),
            ("ST05", "Stake and observe the projected returns before confirming",
             "Frontend computes A = P(1 + r/n)^(nt) client-side for the selected tier",
             "Projected Returns card shows Staked, Interest Earned, Total, and Effective Rate"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-10b Unstake Elixir",
        "table_no": 15,
        "title": "Unstake Elixir Test Case",
        "cases": [
            ("UT01", "Click \"Claim & Unstake\" on a matured position",
             "Backend computes the compound reward and sends principal + reward in LYT to the customer",
             "Position status becomes completed; Elixir balance increases by principal + reward"),
            ("UT02", "Attempt to unstake a position before its maturity date",
             "Backend checks maturityAt against the current time",
             "HTTP 400 \"Not yet matured\"; position remains active"),
            ("UT03", "View an active, non-matured position",
             "Frontend shows the elapsed/remaining days without an unstake action",
             "Progress bar and \"{n} days remaining\" are shown; no Claim & Unstake button appears"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-11 Swap Currency",
        "table_no": 16,
        "title": "Currency Swap Test Case",
        "cases": [
            ("SW01", "Swap ETH to Elixir with MetaMask connected and sufficient ETH",
             "MetaMask sends ETH to the admin address; backend verifies it and pays out Elixir",
             "ETH balance decreases; Elixir balance increases by the converted amount"),
            ("SW02", "Swap RM to Elixir with sufficient RM balance",
             "Backend deducts RM from the ledger and pays out Elixir from the admin wallet",
             "RM balance decreases; Elixir balance increases; no MetaMask prompt for the RM leg"),
            ("SW03", "Select the same currency for both From and To",
             "System validates the two currencies must differ",
             "HTTP 400; swap button remains disabled until a different currency is chosen"),
            ("SW04", "Swap ETH to RM while MetaMask is disconnected",
             "System blocks the on-chain leg of the swap",
             "\"Connect MetaMask to swap ETH.\" prompt is shown; swap is blocked"),
            ("SW05", "Swap RM to ETH with insufficient RM balance",
             "Backend checks the RM ledger balance before proceeding",
             "HTTP 400; balances remain unchanged"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-12 Deposit RM",
        "table_no": 17,
        "title": "Deposit RM Test Case",
        "cases": [
            ("DP01", "Enter a positive RM amount and click Deposit",
             "Backend validates the amount and increments CustomerWallet.RM",
             "RM balance increases by the deposited amount; DEPOSIT transaction recorded"),
            ("DP02", "Enter 0 or a negative amount and click Deposit",
             "Backend validates the amount is positive",
             "HTTP 400; RM balance is unchanged"),
            ("DP03", "Enter non-numeric text into the amount field",
             "Backend rejects a non-numeric amount",
             "HTTP 400; RM balance is unchanged"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-13 Transfer Currency (P2P)",
        "table_no": 18,
        "title": "Transfer Currency Test Case",
        "cases": [
            ("TR01", "Transfer Elixir to a valid recipient wallet address with sufficient balance",
             "MetaMask sends the Elixir on-chain; backend verifies the txHash and records the transfer",
             "Sender's Elixir balance decreases; TRANSFER_OUT / TRANSFER_IN rows recorded"),
            ("TR02", "Transfer RM to a recipient with sufficient RM balance",
             "Backend deducts from the sender's ledger and credits the recipient's ledger directly",
             "Sender's RM decreases and recipient's RM increases; no on-chain transaction required"),
            ("TR03", "Transfer an amount greater than the available balance",
             "Backend/MetaMask checks the balance before sending",
             "HTTP 400 or MetaMask rejection; no balance is moved"),
            ("TR04", "Transfer ETH while MetaMask is disconnected",
             "System blocks the on-chain transfer",
             "\"Connect MetaMask to transfer ETH.\" prompt is shown; transfer is blocked"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-14 View NFT Receipts",
        "table_no": 19,
        "title": "View NFT Purchase Receipts Test Case",
        "cases": [
            ("NR01", "Open the Receipts view after completing an escrow order with delivery confirmed",
             "Frontend calls GET /api/escrow/receipts and reads PurchaseReceipt.receiptsOf on-chain",
             "Minted receipt appears in the list with its token id"),
            ("NR02", "Open the Receipts view with no MetaMask address linked",
             "Backend has no address to query on-chain receipts for",
             "Empty result is returned; no receipts are shown"),
        ],
    },
    {
        "actor": "Customer",
        "usecase": "UC-C-15 Update Profile",
        "table_no": 20,
        "title": "Update Profile Test Case",
        "cases": [
            ("PR01", "Edit Name, Phone and Delivery Address; click Save Changes",
             "Frontend calls PUT /api/auth/profile with the updated fields",
             "\"Profile updated successfully.\" toast appears; new values shown in view mode"),
            ("PR02", "Change Email to an address already used by another account",
             "Backend checks the new email is not used by another account",
             "HTTP 409; email is not updated"),
            ("PR03", "Enter a New Password without providing the correct Current Password",
             "Backend verifies currentPassword before accepting a new one",
             "HTTP 401; password is not changed"),
            ("PR04", "Enter a New Password shorter than 6 characters",
             "Backend validates the minimum password length",
             "\"New password must be at least 6 characters.\" error shown"),
            ("PR05", "Enter mismatching New Password and Confirm New Password values",
             "Frontend validates the two password fields match before submitting",
             "\"New password and confirmation do not match.\" error shown; form not submitted"),
            ("PR06", "Clear the Name field and click Save Changes",
             "Frontend validates the name field is not empty",
             "\"Name cannot be empty.\" error shown; form not submitted"),
        ],
    },

    # ================================================================
    # B. MERCHANT
    # ================================================================
    {
        "actor": "Merchant",
        "usecase": "UC-M-01a/b/d Manage Product Catalog",
        "table_no": 21,
        "title": "Manage Product Catalog Test Case",
        "cases": [
            ("PC01", "Fill Product Name, Category, Price (RM), Stock; click Create Product",
             "Backend validates required fields and checks the plan's product limit before creating the row",
             "New product appears in \"Your Products\" with status Live"),
            ("PC02", "Submit the Create Product form with the Product Name field empty",
             "Backend validates name and priceEth are present",
             "HTTP 400; product is not created"),
            ("PC03", "Click \"Edit\" on an existing product, change the price, and save",
             "Frontend calls PUT /api/products/:id after verifying ownership",
             "Product's price is updated and reflected on the product card"),
            ("PC04", "Click \"Deactivate\" on a Live product",
             "Backend sets isActive to false (soft delete) via DELETE /api/products/:id",
             "Product status changes to Hidden and disappears from the public Shop grid"),
            ("PC05", "Click \"Reactivate\" on a Hidden product while under the plan's product limit",
             "Backend re-runs the plan-limit check and sets isActive to true",
             "Product status changes back to Live and reappears in the public Shop grid"),
            ("PC06", "Attempt to edit a product belonging to a different merchant (e.g. via direct API call)",
             "Backend verifies product.merchantId matches the requester",
             "HTTP 403 \"Not your product\"; no changes applied"),
        ],
    },
    {
        "actor": "Merchant",
        "usecase": "UC-M-01c Check Plan Product Limit",
        "table_no": 22,
        "title": "Plan Product Limit Enforcement Test Case",
        "cases": [
            ("PL01", "Create a 4th product on the Starter plan (limit 3)",
             "Backend counts active products and compares to the Starter plan's limit of 3",
             "HTTP 403 PLAN_LIMIT_REACHED; \"Your Starter plan allows up to 3 active products...\" shown"),
            ("PL02", "Create an 11th product on the Pro plan (limit 10)",
             "Backend counts active products and compares to the Pro plan's limit of 10",
             "HTTP 403 PLAN_LIMIT_REACHED; product is not created"),
            ("PL03", "Create a product while on the Enterprise plan (unlimited)",
             "Backend finds productLimit is null for Enterprise and skips the cap check",
             "Product is created successfully regardless of current product count"),
            ("PL04", "Reactivate a Hidden product that would push the count over the plan limit",
             "Backend re-runs the plan-limit check before reactivating",
             "HTTP 403 PLAN_LIMIT_REACHED; product remains Hidden"),
        ],
    },
    {
        "actor": "Merchant",
        "usecase": "UC-M-02 Manage Purchase Orders / Fulfillment",
        "table_no": 23,
        "title": "Track Purchase Order & Fulfillment Test Case",
        "cases": [
            ("PO01", "Open the \"Track Purchase Order\" tab with incoming orders present",
             "Frontend calls GET /api/orders/merchant and renders one card per order",
             "Orders are listed with buyer info, payment mode, and current fulfillment stage"),
            ("PO02", "Click \"Advance \u2192 Processing\" on an order at stage Order placed",
             "Frontend calls PUT /api/orders/:id/fulfillment with the next stage",
             "Order's stage badge updates to Processing; timeline advances one step"),
            ("PO03", "Select \"4. Delivered\" directly from the stage dropdown",
             "Backend updates fulfillmentStage to 4 directly",
             "Order timeline jumps straight to Delivered; Advance button becomes disabled"),
            ("PO04", "Attempt to update the fulfillment stage of an order belonging to a different merchant",
             "Backend verifies the order's merchantId matches the requester",
             "HTTP 403 \"Not your order\"; stage is not changed"),
            ("PO05", "Advance the stage on an ETH Escrow order that is still funded",
             "System only updates the informational fulfillment stage, not the escrow payout",
             "Fulfillment stage updates, but escrowStatus remains funded until the buyer confirms delivery"),
        ],
    },
    {
        "actor": "Merchant",
        "usecase": "UC-M-03 Manage Subscription",
        "table_no": 24,
        "title": "Subscription Plan & Payment Test Case",
        "cases": [
            ("SB01", "Open the \"Payments\" tab",
             "Frontend calls GET /api/subscription/me",
             "Current plan, product usage, and renewal date are displayed"),
            ("SB02", "Select the Enterprise plan card while currently on Pro",
             "Frontend calls POST /api/subscription/change; backend sets pendingPlan",
             "\"Scheduled\" tag appears on Enterprise; notice shows the change applies next billing cycle"),
            ("SB03", "Select the currently active plan again after queuing a change",
             "Backend clears the previously queued pendingPlan",
             "Pending plan notice disappears; current plan remains unchanged"),
            ("SB04", "Click \"Pay & Apply Plan\" with the correct ETH amount for the pending plan",
             "MetaMask sends ETH to the platform; backend verifies the amount and applies pendingPlan",
             "Plan becomes active; planRenewsAt extends by 30 days; SubscriptionPayment recorded"),
            ("SB05", "Send an ETH amount that does not match the plan's price",
             "Backend verifies the incoming ETH amount against the plan price",
             "HTTP 400 \"Incorrect amount\"; plan is not changed"),
            ("SB06", "Click \"Pay / Renew\" while MetaMask is disconnected",
             "System replaces the pay action with a connect prompt",
             "\"Connect MetaMask to Pay\" button is shown instead of the pay button"),
        ],
    },

    # ================================================================
    # C. ADMIN
    # ================================================================
    {
        "actor": "Admin",
        "usecase": "UC-A-01/02 View Users & Platform Overview",
        "table_no": 25,
        "title": "Admin User Management Test Case",
        "cases": [
            ("AU01", "Open the \"Users\" tab",
             "Frontend calls GET /api/admin/users and GET /api/admin/overview",
             "User table and role-count tiles (customers/merchants/admins) are displayed"),
            ("AU02", "Type a partial name into the search box",
             "Frontend calls GET /api/admin/users?search={term} after a 300ms debounce",
             "Table filters to users whose name, email, code, or wallet matches the term"),
            ("AU03", "Search for a term that matches no user",
             "Backend returns an empty result set",
             "\"No results for '{term}'.\" empty state is shown"),
            ("AU04", "Attempt to open the admin Users API as a logged-in customer",
             "Backend's requireRole(\"admin\") middleware rejects the request",
             "HTTP 403; user cannot view the admin user list"),
        ],
    },
    {
        "actor": "Admin",
        "usecase": "UC-A-04/04a Manage Staking Tiers",
        "table_no": 26,
        "title": "Admin Staking Tier Management Test Case",
        "cases": [
            ("AS01", "Open the \"Staking\" tab",
             "Frontend calls GET /api/admin/staking/tiers and GET /api/admin/staking/positions",
             "Four tier cards (30/90/180/365 days) and the full stakers table are displayed"),
            ("AS02", "Change the 90-day tier's APY from 14 to 16 and click Save",
             "Frontend calls PUT /api/admin/staking/tiers/90; backend updates the StakingTier row",
             "Tier's APY updates to 16%; note confirms existing positions keep their locked-in rate"),
            ("AS03", "Enter a negative value into a tier's APY field and click Save",
             "Backend validates the APY is a non-negative number",
             "\"Enter a valid APY.\" error shown; tier is not updated"),
            ("AS04", "View a staking position opened before an APY change",
             "System reads the apy value stored on the StakePosition itself, not the live tier value",
             "Position continues to display the APY it was created with, unaffected by the tier update"),
        ],
    },
    {
        "actor": "Admin",
        "usecase": "UC-A-05/06 View & Resolve Escrow Disputes",
        "table_no": 27,
        "title": "Resolve Escrow Dispute Test Case",
        "cases": [
            ("AD01", "Open the \"Disputes\" tab with at least one disputed order",
             "Frontend calls GET /api/admin/escrow/disputes",
             "Disputed order appears in the table with product, buyer, seller, asset, and value"),
            ("AD02", "Click \"Release to Seller\" and confirm the dialog",
             "Backend calls PurchaseEscrow.resolveDispute(escrowId, false); order is updated on success",
             "Confirmation dialog appears; on confirming, escrowStatus becomes released, fulfillmentStage 4"),
            ("AD03", "Click \"Refund Buyer\" and confirm the dialog",
             "Backend calls PurchaseEscrow.resolveDispute(escrowId, true); stock restored on success",
             "Order status becomes cancelled; product stock is restored; EscrowRefunded logged"),
            ("AD04", "Click \"Release to Seller\" then dismiss/cancel the confirmation dialog",
             "The native confirm dialog is dismissed before the API call is made",
             "No on-chain call is made; dispute remains open"),
            ("AD05", "Attempt to resolve a dispute while the admin wallet lacks contract owner permissions",
             "The on-chain resolveDispute call reverts",
             "HTTP 500; order state remains disputed and unchanged"),
        ],
    },
    {
        "actor": "Admin",
        "usecase": "UC-A-07 View Subscription Revenue",
        "table_no": 28,
        "title": "Admin Revenue Test Case",
        "cases": [
            ("AR01", "Open the \"Revenue\" tab with subscription payments recorded",
             "Frontend calls GET /api/admin/revenue",
             "Revenue tiles, monthly trend, and the full payment ledger table are displayed"),
            ("AR02", "Open the \"Revenue\" tab with no subscription payments recorded",
             "Backend returns an empty payments list",
             "\"No revenue data\" empty state is shown"),
            ("AR03", "Click \"\u21bb Refresh\" on the Subscription Payments ledger",
             "Frontend re-calls GET /api/admin/revenue",
             "Ledger table reloads with the latest payment records"),
        ],
    },
    {
        "actor": "Admin",
        "usecase": "UC-A-03/08 Treasury Balance & Blockchain Audit Log",
        "table_no": 29,
        "title": "Treasury Balance & Audit Log Test Case",
        "cases": [
            ("AL01", "Leave the admin console open and wait 15 seconds",
             "Frontend polls GET /api/admin/balance on a 15-second interval",
             "Platform Treasury card refreshes with the current ETH and Elixir balances"),
            ("AL02", "Disconnect the RPC/blockchain connection and check the Treasury card",
             "Backend cannot reach the chain to read balances",
             "Status indicator shows \"Chain offline\" instead of \"Chain connected\""),
            ("AL03", "Open the blockchain audit log filtered by eventType=EscrowCreated",
             "Frontend calls GET /api/orders/blockchain/logs?eventType=EscrowCreated",
             "Only EscrowCreated log entries are returned, most recent first"),
        ],
    },
]
